# Aliases
alias crr='cd /workspaces/roserocket'
alias sfish='source ~/.config/fish/config.fish'
alias vfish='vim ~/.config/fish/config.fish'

alias ls='ls -al'

alias gis='git status'
alias gs='git switch'
alias gb='git branch'
alias gd='git diff'
alias gl='git log'
alias gm='git merge'
alias gM='git merge --squash'
alias gf='git pull'
alias gp='git push'
alias ga='git add'
alias gA='git add .'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gsd='git switch develop'
alias gsc='git switch -c'
alias glr='git log --raw'
alias gcam='git commit -am'
alias fetch='git fetch'
alias stashls='git stash list'
alias stashapp='git stash apply'
alias stashpop='git stash pop'

alias rebasedev='git rebase origin/develop'
alias resetconftest='git checkout -- lib/database/rdbms/config_test.go'

alias mgd='make goose-down'
alias mgs='make goose-status'
alias mgu='make goose-up'

alias upd='docker-compose -f docker-compose.personal.yaml up'
alias rapi='make reload-api'
alias rui='make reload-ui'
alias rauth='make reload-auth'
alias rmob='make reload-mob'
alias rplat='make reload-plat'
alias logapi='docker logs roserocket_api_1 --tail 100'
alias logui='docker logs roserocket_ui_1 --tail 100'
alias logdocs='docker logs roserocket_docs_1 --tail 100'
alias lockc='sudo choom -p (ps aux | grep webpack | grep root | awk \'{print $2}\') -n -500'

alias cyopen='npm run cy:open'

# starship init fish | source
